name: Basic Build Workflow
on:
  push:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2

     - name: Print Message
       run: echo "build start" 

     - name: List files
       run: ls -la
  
