name: Basic Build Workflow
on:
  push:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
     - uses: actions/checkout@v2

     - name:  "Current date [DATE]"
       run: date

     - name: "Hello from [REPO_NAME]"
       run: echo "Hello from ${{ github.repository }}"

     - name: "Lists all files in the repo"
       run: ls -R

     - name: "Counts total files"
       run: find . -type f | wc -l
