name: Basic Build Workflow
on:
  push:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
     - uses: actions/checkout@v4

    #  - name:  "Current date [DATE]"
    #    run: date

    #  - name: "Hello from [REPO_NAME]"
    #    run: echo "Hello from ${{ github.repository }}"

    #  - name: "Lists all files in the repo"
    #    run: ls -R

    #  - name: "Counts total files"
    #    run: find . -type f | wc -l
     - name: 'check python version'
       uses: actions/setup-python@v5
       with: 
          python_version: 3.11

     - name: 'Verify Python version'
       run: python --version